#!/bin/ksh -l
#BSUB -a poe
#BSUB -n 20
#BSUB -R "span[ptile=8]"
#BSUB -W 0:40
#BSUB -o /ptmpp2/Guang.Ping.Lou/tmptrk/tracker_fnmoc_00.o%J
#BSUB -e /ptmpp2/Guang.Ping.Lou/tmptrk/tracker_fnmoc_00.o%J
#BSUB -q dev
#BSUB -P NAM-T2O
#BSUB -J grib2_trk1
#BSUB -M 1000
# EXPORT list here
set -x
export envir=prod
export cmodel=fens
export NET=gens
export RUN=fens
export cyc=00
export job=tracker_fens_00

. /meso/save/Guang.Ping.Lou/EMC_verif/trk_glbl/tags/genesis_tracker.v3.4.7/jobs/JTRACKER
