#!/bin/ksh -l
#BSUB -a poe
#BSUB -n 21
#BSUB -R "span[ptile=8]"
#BSUB -W 1:30
#BSUB -o /ptmpp2/Guang.Ping.Lou/tmptrk/tracker_cens_00.o%J
#BSUB -e /ptmpp2/Guang.Ping.Lou/tmptrk/tracker_cens_00.o%J
#BSUB -q dev
#BSUB -J grib2_trk1
#BSUB -M 1000
#BSUB -P NAM-T2O
# EXPORT list here
set -x
export envir=prod
export cmodel=cens
export NET=gens
export RUN=cmce
export cyc=00
export job=tracker_cens_00

. /meso/save/Guang.Ping.Lou/EMC_verif/trk_glbl/tags/genesis_tracker.v3.4.7/jobs/JTRACKER
