#!/bin/ksh -l
#BSUB -a poe
#BSUB -n 21
#BSUB -R "span[ptile=16]"
#BSUB -W 1:30
#BSUB -o /ptmpp2/Guang.Ping.Lou/tmptrk/tracker_gefs_00.o%J
#BSUB -e /ptmpp2/Guang.Ping.Lou/tmptrk/tracker_gefs_00.o%J
#BSUB -q dev
#BSUB -J gefs_trk1
#BSUB -P NAM-T2O
#BSUB -M 1000
# EXPORT list here
set -x
export envir=prod
export cmodel=gefs
export NET=gens
export RUN=gefs
export cyc=00
export job=tracker_gefs_00

. /meso/save/Guang.Ping.Lou/EMC_verif/trk_glbl/tags/genesis_tracker.v3.4.7/jobs/JTRACKER
