#!/bin/ksh -l
#BSUB -a poe
#BSUB -o /ptmpp2/Guang.Ping.Lou/tmptrk/tracker_ukx_12.o%J
#BSUB -e /ptmpp2/Guang.Ping.Lou/tmptrk/tracker_ukx_12.o%J
#BSUB -q dev
#BSUB -n 1
#BSUB -R "affinity[core]"
#BSUB -W 0:40
#BSUB -M 1000
#BSUB -P NAM-T2O
#BSUB -J ukmet_trk1

# EXPORT list here
set -x
export envir=prod
export cmodel=ukmet
export NET=mrf
export RUN=ukmet
export cyc=12
export job=tracker_ukmet_12

. /meso/save/Guang.Ping.Lou/genesis_tracker.v3.4.0/jobs/JTRACKER
