#!/bin/ksh -l
#BSUB -a poe
#BSUB -o /ptmpp2/Guang.Ping.Lou/tmptrk/tracker_emx_00.o%J
#BSUB -e /ptmpp2/Guang.Ping.Lou/tmptrk/tracker_emx_00.o%J
#BSUB -q dev
#BSUB -n 1
#BSUB -R "affinity[core]"
#BSUB -W 0:40
#BSUB -M 2000
#BSUB -P NAM-T2O
#BSUB -J grib2_trk1

set -x
export envir=prod
export cmodel=ecmwf
export NET=us007003
export RUN=ecmwf
export cyc=00
export job=tracker_ecmwf_00

. /meso/save/Guang.Ping.Lou/EMC_verif/trk_glbl/tags/genesis_tracker.v3.4.7/jobs/JTRACKER_test 20180525
