#!/bin/ksh -l
#BSUB -a poe
#BSUB -o /ptmpp2/Guang.Ping.Lou/tmptrk/tracker_cmc_00.o%J
#BSUB -e /ptmpp2/Guang.Ping.Lou/tmptrk/tracker_cmc_00.o%J
#BSUB -q dev
#BSUB -n 1
#BSUB -R "affinity[core]"
#BSUB -W 0:40
####BSUB -M 2000
#BSUB -P NAM-T2O
#BSUB -J cmc_trk1
#
# EXPORT list here
set -x
export envir=prod
export cmodel=cmc
export NET=hourly
export RUN=cmc
export cyc=00
export job=tracker_cmc_00

. /meso/save/Guang.Ping.Lou/EMC_verif/trk_glbl/tags/genesis_tracker.v3.4.7/jobs/JTRACKER

