#!/bin/ksh -l
#BSUB -a poe
#BSUB -n 26
#BSUB -R "span[ptile=16]"
#BSUB -W 0:40
#BSUB -x
#BSUB -o /ptmpp2/Guang.Ping.Lou/tmptrk/tracker_sref_09.o%J
#BSUB -e /ptmpp2/Guang.Ping.Lou/tmptrk/tracker_sref_09.o%J
#BSUB -q dev
#BSUB -M 1000
#BSUB -P NAM-T2O
#BSUB -J sref_trk1
# EXPORT list here
set -x
export envir=prod
export cmodel=sref
export NET=sref
export RUN=sref
export cyc=09
export job=tracker_sref_09

. /meso/save/Guang.Ping.Lou/genesis_tracker.v3.4.0/jobs/JTRACKER
