#!/bin/ksh -l
#BSUB -a poe
#BSUB -o /ptmpp2/Guang.Ping.Lou/tmptrk/tracker_nam_00.o%J
#BSUB -e /ptmpp2/Guang.Ping.Lou/tmptrk/tracker_nam_00.o%J
#BSUB -q dev
#BSUB -n 1
#BSUB -R "affinity[core]"
#BSUB -W 0:40
#BSUB -M 1000
#BSUB -J nam_trk2
#BSUB -P NAM-T2O
set -x
export envir=prod
export cmodel=nam
export NET=nam
export RUN=nam
export cyc=00
export job=tracker_nam_00

. /meso/save/Guang.Ping.Lou/EMC_verif/trk_glbl/tags/genesis_tracker.v3.4.7/jobs/JTRACKER
